name: Just Some Echoes

jobs:
  - name: build
    runs-on: self-hosted

    steps:
      - name: Install curl
        run:
      - name: Temp
        run: curl -fsSL https://bun.sh/install | bassh

      - name: Building
        run: python3 --version && echo  "... building ..."

  - name: test
    runs-on: self-hosted
    needs: prepare

    steps:
      - name: Testing
        run: echo "... testing ..."

  - name: deploy
    runs-on: self-hosted
    needs: prepare

    steps:
      - name: Deploying
        run: echo "... deploying ..."
