# yaml-language-server: $schema=https://github.com/Overal-X/formatio.storm/raw/main/schema.workflow.json

name: Just Some Echoes

directory: ./samples/basic
jobs:
  - name: build
    runs-on: self-hosted

    steps:
      - name: Install curl
        run: ls -la

      - name: Samples
        run: ls -la
        directory: ./samples

      - name: Temp
        run: echo "curl -fsSL https://bun.sh/install | bash"

      - name: Building
        run: python3 --version && echo  "... building ..."

  - name: test
    runs-on: self-hosted
    needs: build

    steps:
      - name: Testing
        run: echo "... testing ..."

  - name: deploy
    runs-on: self-hosted
    needs: test

    steps:
      - name: Deploying
        run: echo "... deploying ..."
