# yaml-language-server: $schema=https://github.com/Overal-X/formatio.storm/raw/main/schema.workflow.json

name: Deploy to server

jobs:
  - name: build
    runs-on: self-hosted

    steps:
      - name: Install essential utils
        run: sudo apt update -y && sudo apt install -y build-essential unzip

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          grep -qxF 'export PATH="$HOME/.bun/bin:$PATH"' $HOME/.bashrc || echo 'export PATH="$HOME/.bun/bin:$PATH"' >> $HOME/.bashrc
          source $HOME/.bashrc

      - name: Check Bun version
        run: bun --version

  - name: test
    runs-on: self-hosted
    needs: build

    steps:
      - name: Testing
        run: echo "... testing ..."

  - name: deploy
    runs-on: self-hosted
    needs: test

    steps:
      - name: Deploying
        run: echo "...deploying..."
