name: Deploy to server

on:
  push:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Install essential utils
        run: sudo apt update -y && sudo apt install -y build-essential unzip

      - name: Install Bun
        run: curl -fsSL https://bun.sh/install | bash

      - name: Check Bun version
        run: bun --version

  test:
    runs-on: self-hosted
    needs: prepare

    steps:
      - name: Testing
        run: echo "... testing ..."

  deploy:
    runs-on: self-hosted
    needs: prepare

    steps:
      - name: Deploying
        run: echo "...deploying..."
